### ISSUE TITLE
[DISCUSSION] Admin DB를 어디에 추가할까요?

### ISSUE THREAD

**Issue by DongWooE** [CBNU-AACP/Admin#11]
**어떤 제안사항인가요?**
저번에 얘기하다가 말았던 Admin을 DB에 추가하는 방법에 대한 논의입니다

2가지 방법이 얘기가 나왔었는데요
- user에 role식으로 추가
- admin이라는 table을 추가

제 생각은요, admin 계정이 많아봣자 3개? 정도 일 것 같아서 table을 하나 
만드는 것에 대한 부담감이 있긴 한데 다른 분들의 의견이 궁금하네요

**함께 논의할 사람을 mention해주세요**
- @L-o-g-a-n 
- @kingyong9169 

**추가 이슈 사항이 있나요?**
없습니다

**기타**

**Comment by kingyong9169** [comment]
이것 참 고민되는 부분이긴하네요.. user에 role로 만들어도 좋고 table을 추가해도 좋을 것 같긴한데..

제 생각은 admin과 실제 서비스의 user와는 전혀 다른 부류라고 생각이 듭니다. admin이 user이자 코스의 관리자(교수자) 기능을 하면 모르겠지만요. 따라서 데이터가 적겠지만 테이블로 관리하는 것이 더 좋다고 생각합니다. 하지만 서비스에서 admin 기능(교수자)이 있거나 추가할 예정이면 user에 role을 만드는게 맞다고 생각합니다. 마지막으로, 사실상 admin은 로그인 기능만 필요하기도 하고 실제로 admin 사이트에서만 사용하기 때문에 실제 서비스인 체크 메이트와 연관지을 필요성이 없다고 생각합니다.

그래서 다른 DB로 관리하여 checkmate, admin(저희만 사용) DB 2개를 운영하는 것도 좋다고 생각합니다.

저도 제가 말을 하면서 헷갈려서 질문 있으시면 남겨주셔여 빠끄~

질문사항
- 혹시 부담감에 대한 고민은 어떤 것이 있나요?

**Comment by DongWooE** [comment]
부담감은 시스템 상의 부담감을 이야기한 거 였습니다 ㅎㅎ
아무래도 table을 하나 추가한다면 그만큼의 공간상의 오버헤드가 존재할테니 말이죠

근데 말씀하신대로 admin을 user 관점에서 출석 기능에 대한 역할을 생각해보았을때
출석 관리자가 되기도 좀 그렇고 출석자가 되는 것도 이상하네요 
**admin table은 따로 만드는 것이 나을 것 같다고 생각이 드네요!**

user의 역할 관점에서 따로 생각은 안해봤는데 도움주셔서 감사합니다 빠끄야

**Comment by sungjindev** [comment]
부담갖지 말고 속 시원히 털어 놓아보아염. 따끄
저도 저번에 이 얘기 나왔을 때부터 지금도 다시 생각해보면 테이블을 하나 따로 만드는 게 낫다고 생각해요.
테이블 하나 만들어서 쓰는 게 더 간단할 것 같기도 하고요~

**Comment by DongWooE** [comment]
부담이 제가 부담되는 것이 아니라 시스템상의 부담을 이야기한건데
다들 제 부담으로 오해를 하시네요 ㅋㅋㅋㅋ

그렇다면 테이블을 하나 추가하는 것으로 합시다 다들 즐코하세요~
