### ISSUE TITLE
[DISCUSSION] jwt사용 제안

### ISSUE THREAD

**Issue by kingyong9169** [CBNU-AACP/Admin#12]
**어떤 제안사항인가요?**
admin 로그인에서 jwt 사용제안입니다.
어제 논의할 때는 단순 로그인이라 jwt 사용을 안해도 되는 것으로 마무리했었는데 생각해보니 admin 사이트를 배포하게 되면 불특정 악질 사용자가 저희 admin을 해킹할 수도 있다고 생각해서ㅋㅋㅋㅋ jwt를 사용하는 것이 어떨까 하고 제안합니다! 또한, 성진이형이 이미 구현했던 프로젝트가 있다고 해서..ㅋㅋㅋㅋㅋㅋ 고거 활용하는 것도 좋다고 생각합니다. 빠끄

**함께 논의할 사람을 mention해주세요**
- @DongWooE 
- @L-o-g-a-n 

**추가 이슈 사항이 있나요?**
X
**기타**
X

**Comment by DongWooE** [comment]
흠 글쎄요

일단 외부에서 admin을 해킹한다는 것은 저희 admin 아이디/비밀번호를 탈취해서 로그인을 하는 것일텐데요
그것은 사실 jwt로 막을 수는 없을 것 같아요...

제가 생각한 jwt를 활용한 로그인을 한다면 아래 2가지 이점이 있을 것 같아요
- 로그인하지 않은 user 또는 권한이 없는 user가 허용되지 않은 서비스를 이용할 경우 제한
- 웹 사이트상의 로그인이 아닌 서버 url post 요청을 통한 로그인 제한

그런데 저희가 구현하는 admin서비스에서 admin이 접근하지 못하는 페이지는 따로 없어서
오히려 jwt를 통해서 구현한다면 아마 로그인 과정에서 형식상의 토큰 발행으로 끝이 날 것 같아요

뭐 또 앞으로 나올 기능들에 의해서 jwt의 필요성이 생길 수도 있지만
지금 당장은 jwt 대신에 다른 기능들에 힘쓰는 것이 낫지 않을까 싶네요

**Comment by sungjindev** [comment]
음, 어제 같이 얘기해봤을 때는 단순 로그인이라서 jwt가 필요 없겠다고 저도 생각했었는데 이번 이슈를 보고 스스로에게 의문점이 생긴 것이 있어요.
서버쪽에 단순 변수식 ID/PW를 가지고 1회 로그인할 때, 각 페이지에서 admin 권한을 가진 사용자가 로그인 되어있는지 안되어있는지에 대한 사용자 검증 처리를 어떻게 할지가 고민이네요.

만약에 JWT를 활용해서 로그인 시 발행해주면 그걸로 자동 로그인과 같은 기능을 구현할 수 있고 쿠키에 가지고 있다가 매 페이지에서 JWT로 사용자 검증을하면 될 것 같긴한데 JWT를 안쓰게되면 어떤 식으로 처리해야될까요? 
JWT 안쓰고 세션을 유지시키는 방법에 대해서 아시는 분 있으시면 코멘트 부탁드려요! 그 두가지 방법을 비교해보고 더 필요한 쪽이나 효율적인 쪽으로 선택하면 좋을 것 같아염. 따끄

**Comment by DongWooE** [comment]
아 근데 다시 생각해보니까 클라이언트 세션관리가 문제가 아니라
admin 서버쪽 url에 직접 접근한다면 문제가 발생할 수도 있겠네요...
아무래도 민감한 api다보니까 안전장치가 필요할 것 같네요

그렇다면 이젠 access-token이냐 refresh-token이냐가 문제가 되겠네요

그리고 추가적으로 이슈인 것은 jwt 로그인 기능 구현 시기에 대한 문제인 것 같아요
jwt가 굉장히 중요한 기능인 것 맞지만 눈에 보이는 기능이 아니기 때문에
원래 계획했던 postman 기능, 메신저 기능처럼 딱 봐도 뭔가 데이터베이스시스템에서 
점수를 높게 쳐줄 기능들 우선 개발하는 것이 낫다고 생각이 들어요

**Comment by sungjindev** [comment]
맞아요 맞아요. 그래서 쓴다고 하면 그냥 기존에 다른 프로젝트에서 만들어놨던 거 가져와서 쓰면 될 것 같아요.
근데 확실히 우선 순위는 좀 후순위로 둬야될 것 같아요.

**Comment by kingyong9169** [comment]
맞습니다 맞습니다 기존 프로젝트 있던 것을 활용하되 우선 순위를 후순위를 두는게 좋을 것 같아요

**Comment by DongWooE** [comment]
좋습니다 빠끄~
