### ISSUE TITLE
[FEATURE] admin-web, admin-server, mysql dockerizing 작업

### ISSUE THREAD

**Issue by DongWooE** [CBNU-AACP/Admin#14]
**어떤 기능을 추가하시나요?**
docker를 활용해서 Admin 서비스가 local에서 뛰울 수 있도록 하는
작업을 할 예정입니다

**어떤 세부 features가 있나요?**
- [x] 각각의 dockerfile 작성
- [x] docker-compose 파일 작성
- [x] Testing

**추가 이슈 사항이 있나요?**
X

**기타**
X

**Comment by sungjindev** [comment]
확인 완료했습니다~ 추가 이슈 사항 부분만 클라이언트 측과 얘기 마치면 되겠네염~ 따끄

**Comment by DongWooE** [comment]
**dockerfile 실행하기**

1. dockerfile이 있는 폴더에 위치
2. image 생성
`docker build -t {image 이름} .` 
3. container 실행
`docker run -it -p {해당 서비스에 원래 설정된 포트}:{외부에서 띄어줄 포트}`
※반드시 -it 옵션을 붙인다 그 이유는 -it는 대화형 터미널로 하지않으면 docker가 개발모드로 실행되지않아서 
이상한 포트로 실행됨
[관련 stackoverflow](https://stackoverflow.com/questions/61047861/cant-run-react-app-with-docker-container/61048016)

**Comment by DongWooE** [comment]
[pool에 대해서](https://darrengwon.tistory.com/688)
