### ISSUE TITLE
[DISCUSSION] DROP TABLE시 CASCADE 옵션에 관한 논의사항

### ISSUE THREAD

**Issue by sungjindev** [CBNU-AACP/Admin#17]
**어떤 제안사항인가요?**
다른 테이블과 관계성을 가지고 있는 테이블에 대한 DROP TABLE 기능 구현 시, CASCADE 옵션을 줄지 말지에 대한 논의.

**함께 논의할 사람을 mention해주세요**
- @DongWooE 
- @kingyong9169 

**추가 이슈 사항이 있나요?**
X

**기타**
관계성을 가지고 있는 테이블을 지우려고 하면 SQL 상에서 에러 메세지를 내뱉었던 것으로 기억하는데, 확실치 않아서
이 부분에 대한 조사와 추가적인 논의가 필요할 것 같습니다.

**Comment by DongWooE** [comment]
TABLE에도 cascade 옵션을 줄 수 있네요!
아래 블로그를 참조했어요
[DROP TABLE](https://devjhs.tistory.com/432)

**Comment by sungjindev** [comment]
오오 좋아요. 그러면 TABLE에도 CASCADE 옵션 주는 것으로 개발할까요?

**Comment by kingyong9169** [comment]
넵 좋습니당 CASCADE옵션 주는 것으로 갑시당!
