### ISSUE TITLE
[DISCUSSION] 기존 서비스와 통합 시에 레포지토리 관련 논의입니다

### ISSUE THREAD

**Issue by DongWooE** [CBNU-AACP/Admin#18]
**어떤 제안사항인가요?**
기존 서비스와의 통합 시 깃헙 레포지토리를 어떻게 하느냐에 대한 몇가지 고민 중인게 있어요
다른 팀원분들의 생각을 물어보고 싶어요!

- 새로운 레포지토리를 만든 후에 기존 Client,Server,Admin 레포지토리 파일들을 합친다
- 지금의 Admin 레포지토리에 이전 Client, Server 파일들을 갖고 와서 현재 합친다
- 다른 방법들을 찾아본다

**함께 논의할 사람을 mention해주세요**
- @L-o-g-a-n 
- @kingyong9169 

**추가 이슈 사항이 있나요?**
X

**기타**
X

**Comment by kingyong9169** [comment]
음 혹시 통합하려는 이유가 있나요?

**Comment by DongWooE** [comment]
데이터베이스 시스템의 과제를 제출하기 위해서 기존 코드와 같이 묶은 다음에 github 주소만을 제출하기 위해서 예요

**Comment by kingyong9169** [comment]
Admin 주소만 제출하면 되지 않나요? 
기존 코드라는게 기존 서버 코드를 말씀하시는 건가요?

아니면 만약 저희가 하는 프로젝트가 뭔지 알려드리고 싶으시면
```
DataBaseSystem project repository: http..
our service project repository: http.. 
```
이런식으로 주소 여러 개를 제출해도 될 것 같아요!

만약 이 이유라면 저는 다른 작업에 신경쓰는 것이 더 좋다고 생각합니다.

**Comment by sungjindev** [comment]
어어 나두 사실 통합하려는 이유에대해 물어보려고 했는데 동용이가 물어봐놨네!
나도 동용이랑 같은 생각이야~

그냥 레포 나뉘더라도 다 보여주고 싶으면 레포 여러개 보내줘도 되지 않을까 생각!

**Comment by DongWooE** [comment]
교수님께서 admin만을 확인하는 것을 방지하기 위해서 통합을 얘기한 것인데
두 분 생각이 그렇다면 현재 admin만을 docker-compose로 묶는 작업만을 진행할게요

하지만 나중에 발표 시에 저희의 E-R diagram은 메인 서비스에 있는 DB를 나타낸 것이라는 것을
언급해줘야할 것 같아요

왜냐하면 admin 자체에는 DB가 따로 존재하지 않고 존재하더라도 DB를 통해서 실제 작업이 이뤄지는 것
메인 서비스에 있기 때문이예요
