### ISSUE TITLE
[Discussion] 기존 서비스와의 DB 공유 작업

### ISSUE THREAD

**Issue by DongWooE** [CBNU-AACP/Admin#20]
### 문제

- 현재 Admin만을 독립적인 docker container로 묶으면 기존 서비스와의 DB공유가 안됨
- 기존 서비스를 갖고 와서 하나의 레포지토리에 넣는 것은 부담스러움

### 해결방안

- heroku에 기존 서비스 api와 같이 원격 DB를 올린다
- 현재 Admin api를 원격 DB와 연결한다

=> 원격 DB 하나로 Admin과 기존 서비스의 DB 공유 가능

**어떻게 생각하시나요?**
- @kingyong9169 

**추가 이슈 사항이 있나요?**

**기타**
- 성진이형이 로그인하고 제가 이거 할 거 같은데 지금은 정보보호 공부중이라 저녁먹고 할게요

**Comment by kingyong9169** [comment]
클라이언트까지 같이 묶어야 하나요? 필요하다면 admin server, 실제 서비스 서버를 같이 묶는 것은 어떤가요?

**Comment by DongWooE** [comment]
클라이언트는 따로 묶이지는 않고요 
현재 레포지토리에는 admin-server, admin-web만 묶인 채로 있습니다

실제 서비스의 api와 DB를 원격 서버에 올려서
현재 admin-server의 env값만 바꿔서 연결시킵니다

결론은 현재 레포지토리에 기존 서비스 api든 클라이언트든 코드가 추가되진 않을거예요!
