### ISSUE TITLE
[DISCUSSION] 로그인과 같은 비주류 라우터 개발에 Sequelize 사용 가능 여부

### ISSUE THREAD

**Issue by sungjindev** [CBNU-AACP/Admin#22]
**어떤 제안사항인가요?**
로그인과 같은 라우터를 개발할 때, 즉 Admin 프로젝트의 핵심이 되는 쿼리문 처리 관련 API가 아닌 라우터 개발 중 Sequelize를 사용하는 것에 대한 생각을 듣고 싶습니다. 이러한 비주류 라우터 개발 시 Sequelize 사용해도 될까요?

**함께 논의할 사람을 mention해주세요**
- @DongWooE 

**추가 이슈 사항이 있나요?**
X

**기타**
X

**Comment by DongWooE** [comment]
흠 글쎄요 제 생각에는 아무래도 시퀄라이즈보다는 mysql2의 문법을 사용하는 편이 나을 것 같아요

그 이유는 시퀄라이즈 설정에 따른 코드들이 더 들어가고 전체적인 통일성을 헤칠 거 같아요

그래서 시퀄라이즈든 그냥 mysql2든 하나로만 해서 다 만드는게 나을 것 같네요!
어차피 mysql2는 만든 코드가 별로 없어서 시퀄라이즈로 아예 갈거면 가는 것도 나쁘지 않을 거 같네요

**Comment by DongWooE** [comment]
참고로 sequelize에서도 sequelize.query를 사용해서 query를 사용할 수 있어요!

**Comment by sungjindev** [comment]
오...? 으아닛 그러면 시퀄라이즈를 사용하는 건 어떻게 생각하세요?
쿼리까지 거기서 바로 날릴 수 있다면 너무 좋을 것 같은데!
"시퀄라이즈+ 시퀄라이즈 쿼리" 이 조합으로 갈까요?

**Comment by DongWooE** [comment]
넵 좋습니다 그러면 app.js에 mysql2를 사용해서 db connection하는 코드가 있는데
걔도 sequelize.sync로 바꿔주시면 감사하겠습니다

**Comment by sungjindev** [comment]
옙 좋습니다~ 제가 그 부분은 로그인 작업하면서 같이 작업할게요.
이슈 닫겠습니다.
