### ISSUE TITLE
[DISCUSSION] 외부에서 heroku DB connection 안되는 오류

### ISSUE THREAD

**Issue by sungjindev** [CBNU-AACP/Admin#27]
**어떤 제안사항인가요?**
외부 환경에서 heroku DB connection 안되는 오류 해결이 필요합니다.

**함께 논의할 사람을 mention해주세요**
- @DongWooE 

**추가 이슈 사항이 있나요?**
X

**기타**
X

**Comment by DongWooE** [comment]
sequelize로 바꾸면서 mysql에 들어가는 환경변수에서 변화가 생겼네여

poolConnection을 하기 위한 user이고 sequelize에 들어가는 환경변수는 username이네요
