### ISSUE TITLE
[DISCUSSION] 산학 프로젝트 목차에 '구현방법'을 추가하는 것에 대한 논의

### ISSUE THREAD

**Issue by DongWooE** [CBNU-AACP/Admin#28]
**어떤 제안사항인가요?**
산학 프로젝트 목차에 '구현방법'을 추가하라는 것에 대해서
교수님께서 언급하셨다는 흉흉한 소문이 돌고 있습니다

저 부분을 추가할 필요가 있을까에 대해서 여러분들의 
생각은 어떠하신가요?

**함께 논의할 사람을 mention해주세요**
- @L-o-g-a-n 
- @kingyong9169 

**추가 이슈 사항이 있나요?**
X

**기타**
X

**Comment by kingyong9169** [comment]
음 제 생각은 저희 발표자료에 있는 요구사항 분석에도 구현 로직과 흐름, 어떤 소프트웨어를 사용하는지도 충분히 나와 있기 때문에 "구현방법"은 추가하지 않아도 된다고 생각합니다!
