### ISSUE TITLE
[DISCUSSION] API BackLog

### ISSUE THREAD

**Issue by DongWooE** [CBNU-AACP/Admin#34]
# API backlog

#### API BASIC SETTING
- [X] express.js 구조 잡기
- [X] Dockerizing
- [X] 기존 Remote DB 연동

#### Login
- [X] API 및 모델 구조 잡기
- [X] winston 로그 작업
- [X] Login, Logout 만들기
- [X] jwt 토큰 schema 및 api 만들기

#### Database CRUD
- [X] 데이터베이스 목록 불러오기
- [X] 데이터베이스 만들기 
- [X] 데이터베이스 삭제하기

#### Table CRUD
- [X] 테이블 목록 불러오기
- [X] 테이블 만들기
- [X] 테이블 삭제하기

#### ROW CRUD
- [x] 테이블에 요소 추가하기
- [x] 테이블에 요소 삭제하기
- [x] 테이블에 요소 수정하기
- [x] 테이블에 있는 모든 요소 불러오기

~~API DOC~~
~~- [ ] API 주소, http 메소드를 담을 schema 만들기~~
~~- [ ] API 주소들 목록, 각각의 http 메소드를 담을 API 만들기~~

#### 기타
- [x] Normalization 테이블 만들기
- [x] view, indexing 방법 논의
- [x] 반환형관련해서는 클라랑 합의 필요

**Comment by DongWooE** [comment]
아 참고로 어제 클라쪽하고 회의 후에 작성합 겁니다~

**Comment by sungjindev** [comment]
큰 흐름은 모두 확인하였습니다~ 이따 회의 때 다시 한번 점검해봅시다.
