### ISSUE TITLE
[FIX] 로그인 서버 오류

### ISSUE THREAD

**Issue by kingyong9169** [CBNU-AACP/Admin#49]
<img width="479" alt="스크린샷 2021-12-19 오전 12 30 07" src="https://user-images.githubusercontent.com/62797441/146646508-1c0bac70-eff9-4935-8436-4b6d7dda7f58.png">
post 요청을 보낼 때, 다음과 같은 데이터로 보내면 오류가 발생합니다. admins에 직접 데이터를 넣어 놓고 admins에 있던 아이디, 패스워드를 입력했습니다.

<img width="1043" alt="스크린샷 2021-12-19 오전 12 24 57" src="https://user-images.githubusercontent.com/62797441/146646525-a5944d4f-879e-4425-b2ee-b73b0beacaa4.png">
docker에서 이런 오류가 발생합니다. 해결해주십사 이슈로 남깁니다.

**Comment by sungjindev** [comment]
<img width="423" alt="스크린샷 2021-12-19 오후 5 04 54" src="https://user-images.githubusercontent.com/77658361/146668414-9cd68f8d-a8fc-4dd4-937a-3d942ab325af.png">
위처럼  데이터베이스시스템 교과목 최종 프로젝트 발표를 위해 admins 테이블의 schema를 변경했었는데  이 부분이 문제가 된 것 같아요~
금방 수정해놓고 반영해놓겠습니다.
