### ISSUE TITLE
[FEATURE] 쿠키를 활용한 토큰 인증 방식에서 헤더를 활용하도록 바꾸기

### ISSUE THREAD

**Issue by sungjindev** [CBNU-AACP/Admin#51]
**어떤 기능을 추가하시나요?**
쿠키를 활용한 토큰 인증 방식에서 헤더를 활용하도록 바꾸기.

**어떤 세부 features가 있나요?**
- [x] 쿠키 방식을 헤더 방식으로 바꾸기
- [x] CSRF 같은 보안적인 이슈 해결하기

**추가 이슈 사항이 있나요?**
없습니다.

**기타**
작업 시간이 다소 소요될 것으로 보입니다.

**Comment by kingyong9169** [comment]
헤더를 활용한다는게 쿠키 방식을 헤더 방식으로 바꾸는게 아니고 쿠키에 있는 jwt를 헤더에 담아서 요청을 보내는 방식입니다!
<img width="723" alt="스크린샷 2021-12-21 오후 1 24 03" src="https://user-images.githubusercontent.com/62797441/146870801-66864a1d-0ead-47c2-bbaa-1c9b7a9915d0.png">

프론트엔드에서 위 사진처럼 보내줄 겁니다!

**Comment by sungjindev** [comment]
어라 뭔가 조금 이상한게 토큰을 Auth 헤더에 담아서 보내면 굳이 쿠키를 사용할 필요가 없지 않나요?
https://velog.io/@cada/%ED%86%A0%EA%B7%BC-%EA%B8%B0%EB%B0%98-%EC%9D%B8%EC%A6%9D%EC%97%90%EC%84%9C-bearer%EB%8A%94-%EB%AC%B4%EC%97%87%EC%9D%BC%EA%B9%8C

위의 글 참조해서 추후에 Authorization 헤더 Bearer에 JWT를 담아 보낼 예정입니다.

**Comment by kingyong9169** [comment]
> 어라 뭔가 조금 이상한게 토큰을 Auth 헤더에 담아서 보내면 굳이 쿠키를 사용할 필요가 없지 않나요? https://velog.io/@cada/%ED%86%A0%EA%B7%BC-%EA%B8%B0%EB%B0%98-%EC%9D%B8%EC%A6%9D%EC%97%90%EC%84%9C-bearer%EB%8A%94-%EB%AC%B4%EC%97%87%EC%9D%BC%EA%B9%8C
> 
> 위의 글 참조해서 추후에 Authorization 헤더 Bearer에 JWT를 담아 보낼 예정입니다.

이 블로그에서 말한 쿠키는 사용자의 id, 비밀번호를 직접 쿠키에 저장한다는 뜻이네요. 쿠키를 사용하는 것은 jwt를 저장하기 위한 수단입니다. 또한, 이 블로그의 헤더는 토큰의 구성 요소를 뜻하는 것 같아요. 만약 쿠키를 안쓰면 서버로부터 받은 jwt는 어떻게 저장하나요?

https://velog.io/@junghyeonsu/%ED%94%84%EB%A1%A0%ED%8A%B8%EC%97%90%EC%84%9C-%EB%A1%9C%EA%B7%B8%EC%9D%B8%EC%9D%84-%EC%B2%98%EB%A6%AC%ED%95%98%EB%8A%94-%EB%B0%A9%EB%B2%95
이 글 읽어보시길 바랍니다~

**Comment by kingyong9169** [comment]
> > 어라 뭔가 조금 이상한게 토큰을 Auth 헤더에 담아서 보내면 굳이 쿠키를 사용할 필요가 없지 않나요? https://velog.io/@cada/%ED%86%A0%EA%B7%BC-%EA%B8%B0%EB%B0%98-%EC%9D%B8%EC%A6%9D%EC%97%90%EC%84%9C-bearer%EB%8A%94-%EB%AC%B4%EC%97%87%EC%9D%BC%EA%B9%8C
> > 위의 글 참조해서 추후에 Authorization 헤더 Bearer에 JWT를 담아 보낼 예정입니다.
> 
> 이 블로그에서 말한 쿠키는 사용자의 id, 비밀번호를 직접 쿠키에 저장한다는 뜻이네요. 쿠키를 사용하는 것은 jwt를 저장하기 위한 수단입니다. 만약 쿠키를 안쓰면 서버로부터 받은 jwt는 어떻게 저장하나요?

**Comment by sungjindev** [comment]
> > 어라 뭔가 조금 이상한게 토큰을 Auth 헤더에 담아서 보내면 굳이 쿠키를 사용할 필요가 없지 않나요? https://velog.io/@cada/%ED%86%A0%EA%B7%BC-%EA%B8%B0%EB%B0%98-%EC%9D%B8%EC%A6%9D%EC%97%90%EC%84%9C-bearer%EB%8A%94-%EB%AC%B4%EC%97%87%EC%9D%BC%EA%B9%8C
> > 위의 글 참조해서 추후에 Authorization 헤더 Bearer에 JWT를 담아 보낼 예정입니다.
> 
> 이 블로그에서 말한 쿠키는 사용자의 id, 비밀번호를 직접 쿠키에 저장한다는 뜻이네요. 쿠키를 사용하는 것은 jwt를 저장하기 위한 수단입니다. 또한, 이 블로그의 헤더는 토큰의 구성 요소를 뜻하는 것 같아요. 만약 쿠키를 안쓰면 서버로부터 받은 jwt는 어떻게 저장하나요?
> 
> https://velog.io/@junghyeonsu/%ED%94%84%EB%A1%A0%ED%8A%B8%EC%97%90%EC%84%9C-%EB%A1%9C%EA%B7%B8%EC%9D%B8%EC%9D%84-%EC%B2%98%EB%A6%AC%ED%95%98%EB%8A%94-%EB%B0%A9%EB%B2%95 이 글 읽어보시길 바랍니다~

GET /resource HTTP/1.1
Host: server.example.com
Authorization: Bearer eyJhbGciOiJIUzI1NiIXVCJ9TJV...r7E20RMHrHDcEfxjoYZgeFONFh7HgQ

위에처럼 토큰값 자체를 Auth헤더 Bearer에 담는 것으로 알고있는데 아닌가요?
헤더에서 값을 읽어서 클라에서 따로 저장해야되는 것으로 알고있습니다.

아래 글 참조했어요~
https://stackoverflow.com/questions/33265812/best-http-authorization-header-type-for-jwt
