### ISSUE TITLE
[DISCUSSION] desc 테이블 이름 + getPKs api 요청입니다.

### ISSUE THREAD

**Issue by kingyong9169** [CBNU-AACP/Admin#52]
**어떤 제안사항인가요?**
기존에 있던 `desc 테이블 이름`(@DongWooE)  api와 `getPKs`(@L-o-g-a-n) 를 합치는 api요청입니다.

As-is: 클라이언트에서 `desc 테이블 이름` 요청 -> 서버로부터 받은 response 데이터 가공을 거쳐서 다시 getPKs 요청
때문에 요청을 2번 보내야하는 비효율성 + 응답 시간이 오래 걸리는 이슈

To-be: 클라이언트에서 `desc 테이블 이름` 요청 -> 서버로부터 기존 `desc 테이블 이름`에 대한 데이터 + getPKs를 통해 받는 데이터를 response로 받음

구현 예상 과정:
- `desc 테이블 이름`을 통해 받은 데이터를 아래 함수를 통해 가공하여 getPks에 있는 쿼리문 실행
- desc, getPKs을 통해 얻은 데이터를 배열 혹은 객체 리터럴에 넣어 클라이언트에 response 보내주기

아래는 클라이언트에서 `desc 테이블 이름`요청을 통해 받은 response 데이터를 가공하는 함수입니다. 참고해주시면 될 것 같습니다!

``` js
export default function dataToKey(schemaData) {
  const FK = [];
  const schema = schemaData.reduce((schema, column) => {
    if (column.Key === "PRI") return { ...schema, [`${column.Field}`]: "PK" };
    if (column.Key === "MUL") FK.push(column.Field);
    return schema;
  }, {});
  return { ...schema, FK: [...FK] };
}
```

**함께 논의할 사람을 mention해주세요**
- @DongWooE 
- @L-o-g-a-n 

**추가 이슈 사항이 있나요?**

**기타**

**Comment by sungjindev** [comment]
따로 desc 라우터만 사용하는 용도가 있다던지 그러지만 않으면 합쳐도 괜찮을 것 같아요~
따로 desc 라우터만 필요하지는 않나요?

**Comment by DongWooE** [comment]
확인했습니다!

**Comment by kingyong9169** [comment]
> 따로 desc 라우터만 사용하는 용도가 있다던지 그러지만 않으면 합쳐도 괜찮을 것 같아요~ 따로 desc 라우터만 필요하지는 않나요?

desc라우터는 테이블 스키마 데이터를 받는 목적인데 합쳐서 desc에 요청하는 데이터를 같이 보내주시면 상관없습니다!

**Comment by kingyong9169** [comment]
> 확인했습니다!

감사합니다!
