### ISSUE TITLE
[DISCUSSION] mysql sequelize 사용 여부

### ISSUE THREAD

**Issue by DongWooE** [CBNU-AACP/Admin#7]
**어떤 제안사항인가요?**
mysql과 연동하는 부분에 있어서 sequelize를 사용해야할지 여부에 있어서 고민입니다
어제 잠깐 찾아본 결과 mysql2를 사용해서 직접 로컬 db와 연결을 하려면
query를 할때마다 mysql과 연결을 해주어야하는 이슈가 있습니다 그에 따라 코드양도 늘어나고요

하지만 mysql과 직접 연결을 통해서 새롭게 공부하게 되는 내용도 있고 
아무래도 데이터베이스 시스템에서 sequelize에 대한 내용을 직접 다룬 적이 없기 때문에
조금 고민이 되는 부분이네요...

**함께 논의할 사람을 mention해주세요**
- @L-o-g-a-n 

**추가 이슈 사항이 있나요?**
자세한 코드 내용는 pullrequest #3 을 확인해주세요!

**기타**

**Comment by sungjindev** [comment]
"query를 할때마다 mysql과 연결을 해주어야하는 이슈" 이러한 이슈에 대해서 생각해보진 못했는데 이런 일이 있다니
여간 번거로운 일이 아닐 수가 없겠군요. 
전 시퀄라이즈를 쓰고 싶지만 교수님이 이 부분에 대해서 어떻게 생각하실지가 뽀인트라고 생각합니다.
한번 이 부분에 대해서 정리를해서 교수님께 메일을 보내보는 게 어떨까 생각해봅니다. 빠끄

**Comment by DongWooE** [comment]
예얍 내일 한번 여쭤보겠습니다 빠끄~

**Comment by sungjindev** [comment]
네 좋습니다~ 답장오면 다시 한번 같이 얘기해보고 싶지뭐얌, 빠끄
