### ISSUE TITLE
[DISCUSSION] issue, pr 템플릿 제안 및 merge방식 제안

### ISSUE THREAD

**Issue by kingyong9169** [CBNU-AACP/Admin#8]
**어떤 제안사항인가요?**
1. issue, pr 템플릿에 보기 쉬운 이모지를 넣는 것을 제안합니다. 이유는 시커먼 화면에 생동감을 줘서 딱딱함을 줄이기 위해서입니다~
2. 커밋 히스토리가 잘 보이기 위해 rebase merge 혹은 squash merge를 제안합니다. 다만 squash merge는 커밋 기록이 pr단위로 생기기 때문에 하나의 pr안에 여러 개의 커밋을 해도 결국 커밋은 1개로 돼서.. 그러고 싶진 않습니다ㅎㅎ 결론은 rebase merge를 제안합니다.

**함께 논의할 사람을 mention해주세요**
- @DongWooE 
- @L-o-g-a-n 

**추가 이슈 사항이 있나요?**
없습니다!

**기타**
없습니다!

**Comment by DongWooE** [comment]
1. 좋은거같아요! 추천하는 이모지가 따로 있으시나요?
2. 어제는 분기점에 대해서 생각했었는데 커밋 히스토리가 잘 보이기 위함이 굉장히 좋은것같네요
전 그런 부분에 있어서 rebase도 동의하고 squash도 괜찮은 방법 같아요!

**Comment by sungjindev** [comment]
저는 rebase가 쓰고 싶습니다. 커밋은 제 자극제이기 때문이죠. 빠끄

**Comment by WonJoongLee** [comment]
지나가다가 재밌는 이슈가 보여서 댓글 남깁니다! rebase merge를 사용하면 충돌 시 매 커밋마다 충돌을 해결해줘야 하는 어려움이 있어서 이 부분도 고려해보시면 좋을 것 같습니다. 파이팅💪

**Comment by DongWooE** [comment]
> 지나가다가 재밌는 이슈가 보여서 댓글 남깁니다! rebase merge를 사용하면 충돌 시 매 커밋마다 충돌을 해결해줘야 하는 어려움이 있어서 이 부분도 고려해보시면 좋을 것 같습니다. 파이팅💪

그러한 이슈가 있는지는 몰랐는데 감사합니다! 좋은 하루 보내세요 'WongJoongLee' 님

**Comment by sungjindev** [comment]
> 지나가다가 재밌는 이슈가 보여서 댓글 남깁니다! rebase merge를 사용하면 충돌 시 매 커밋마다 충돌을 해결해줘야 하는 어려움이 있어서 이 부분도 고려해보시면 좋을 것 같습니다. 파이팅💪

이런 누추한 곳에 귀한 분이 ㅎㅎ 코멘트 감사합니다.
