### ISSUE TITLE
[DISCUSSION] 설계 이슈 템플릿을 제안합니다.

### ISSUE THREAD

**Issue by kingyong9169** [CBNU-AACP/Admin#9]
**어떤 제안사항인가요?**
설계 이슈 템플릿을 제안합니다. 기존 기능 이슈와 다른 점을 말씀드리겠습니다.

설계 이슈 : 추상적으로 어떤 비즈니스 로직과 기능들이 들어갈지 client, server 파트 모두 참여하는 공간. 예를 들어, DB crud 페이지에 꼭 필요한 기능

기능 이슈 : client, server 파트를 나누어 각자 구현해야 할 부분을 자세히 적는 공간. 예를 들어, client의 경우 DB crud 기능을 어떤 스택을 사용하고 애니메이션, 버튼 UI 등등 자세한 기능을 적습니다.

**함께 논의할 사람을 mention해주세요**
- @DongWooE 
- @L-o-g-a-n 

**추가 이슈 사항이 있나요?**

**기타**

**Comment by DongWooE** [comment]
설계 이슈와 기능 이슈는 그럼 1대1 관계에 있는 것인가요?

**Comment by sungjindev** [comment]
Labels만 잘 구분해서 달면 취지도 좋고 여러모로 좋을 것 같아요~

**Comment by kingyong9169** [comment]
> 설계 이슈와 기능 이슈는 그럼 1대1 관계에 있는 것인가요?

1대 다 입니다ㅎㅎ
